export const ROLES = {
  FULL_STACK: "FULL_STACK",
  FRONT_END: "FRONT_END",
  BACK_END: "BACK_END",
  DATA_ENGINEER: "DATA_ENGINEER",
  DEVOPS: "DEVOPS",
};

export const UserManagers = {
  MANAGER_1: "MANAGER_1",
  MANAGER_2: "MANAGER_2",
  MANAGER_3: "MANAGER_3",
  MANAGER_4: "MANAGER_4",
};

export const EmploymentTypes = {
  FULL_TIME: "FULL_TIME",
  PART_TIME: "PART_TIME",
  INTERN: "INTERN",
};

export const PROJECTS = {
  PROJECT_1: "PROJECT_1",
  PROJECT_2: "PROJECT_2",
  PROJECT_3: "PROJECT_3",
  PROJECT_4: "PROJECT_4",
};
